In [ ]:
pip install pandas

In [ ]:
d=[1,2,3,4,5]
d=pd.Series(d)
d

In [ ]:
d={
    "name":["arsalan","faheem","sibtain"],
     "age":[24,24,24],
     "city":["pulwama","srinagar","srinagar"]
    }

In [ ]:
print(d)

In [ ]:
d2 = pd.DataFrame(d)
d2

In [5]:
import pandas as pd

In [4]:

df=pd.read_csv(r"H:\datasets\archive\train.csv")




df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [8]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
df.shape

(891, 12)

In [10]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [11]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [15]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [26]:
df.iloc[0,3]

'Braund, Mr. Owen Harris'

In [28]:
df.loc[714,"Name"]

'Greenberg, Mr. Samuel'

<bound method DataFrame.sum of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [31]:
df.loc[:,"Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [33]:
df.loc[0,"Name"]="arsalan"

In [36]:
df.iloc[0,3]="ayan"

In [37]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,ayan,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [39]:
df.sort_values(by="Fare",ascending=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
271,272,1,3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0000,NaN,S
597,598,0,3,"Johnson, Mr. Alfred",male,49.0,0,0,LINE,0.0000,NaN,S
302,303,0,3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,LINE,0.0000,NaN,S
633,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0000,NaN,S
277,278,0,2,"Parkes, Mr. Francis ""Frank""",male,NaN,0,0,239853,0.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C

In [55]:
df.sort_values(by="Fare",ascending=False,inplace=True)

In [56]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S

In [57]:
df["Age"].max()

80.0

In [58]:
df["Age"].min()

0.42

In [60]:
df["Fare"].mean()

np.float64(32.204207968574636)

In [47]:
df.sort_values(by="Fare",ascending=False,inplace=True)

In [45]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
...,...,...,...,...,...,...,...,...,...,...,...,...
633,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0000,NaN,S
413,414,0,2,"Cunningham, Mr. Alfred Fleming",male,NaN,0,0,239853,0.0000,NaN,S
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0000,NaN,S
732,733,0,2,"Knight, Mr. Robert J",male,NaN,0,0,239855,0.0000,NaN,S
674,675,0,2,"Watson, Mr. Ennis Hastings",male,NaN,0,0,239856,0.0000,NaN,S

In [61]:
df["Fare"].sum()

np.float64(28693.9493)

In [63]:
df["Age"].isnull().sum()

np.int64(177)

In [64]:
df["Age"].notnull().sum()

np.int64(714)

In [65]:
df["Name"].count()

np.int64(891)

In [11]:
alive=df[(df["Age"]>18) &
        (df["Sex"]=="female")&
        (df["Survived"]==1)
        ]

In [12]:
alive

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [17]:
d1=df[['Age','Name','Sex']]

In [18]:
d1.head()

    Age                                               Name     Sex
0  22.0                            Braund, Mr. Owen Harris    male
1  38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2  26.0                             Heikkinen, Miss. Laina  female
3  35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4  35.0                           Allen, Mr. William Henry    male

In [19]:
df[df['Age']>18]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [20]:
alive.shape

(151, 12)

In [27]:
df[df['Name'].str.contains("Rose")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
855,856,1,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,392091,9.35,NaN,S

In [25]:
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [26]:
df["Age"].value_counts()

Age
24.00    30
22.00    27
18.00    26
19.00    25
28.00    25
         ..
36.50     1
55.50     1
0.92      1
23.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [28]:
df['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [29]:
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [32]:
df[df['Name'].isin(['Braund, Mr. Owen Harris'])]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [33]:
df.replace('Braund, Mr. Owen Harris','arsalan',inplace=True)

In [34]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,arsalan,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Arsalan", "Rahul", "Ayesha", "Zaid", "Sara"],
    "Age": [24, 17, 22, 30, 19],
    "City": ["Pulwama", "Delhi", "Srinagar", "Delhi", "Mumbai"],
    "Marks": [85, 72, 91, 65, 88]
})

Level 1 — Basic

1. Print the DataFrame.

2. Display the first 3 rows.

3. Display the last 2 rows.

4. Find the shape of the DataFrame.

5. Display all column names.

6. Display the data types.

In [7]:
df

      Name  Age      City  Marks
0  Arsalan   24   Pulwama     85
1    Rahul   17     Delhi     72
2   Ayesha   22  Srinagar     91
3     Zaid   30     Delhi     65
4     Sara   19    Mumbai     88

In [9]:
df.head(3)

      Name  Age      City  Marks
0  Arsalan   24   Pulwama     85
1    Rahul   17     Delhi     72
2   Ayesha   22  Srinagar     91

In [10]:
df.tail(2)

   Name  Age    City  Marks
3  Zaid   30   Delhi     65
4  Sara   19  Mumbai     88

In [11]:
df.shape

(5, 4)

In [13]:
df.shape[0]

5

In [14]:
df.shape[1]

4

In [22]:
df.columns

Index(['Name', 'Age', 'City', 'Marks'], dtype='object')

In [15]:
df.dtypes

Name     object
Age       int64
City     object
Marks     int64
dtype: object

Level 2 — Selecting

7. Display only the Name column.

8. Display Name and Marks.

9. Using iloc, display the first row.

10. Using loc, display the City of row 2.

In [30]:
df.loc[:,"Name"]

0    Arsalan
1      Rahul
2     Ayesha
3       Zaid
4       Sara
Name: Name, dtype: object

In [43]:
df.iloc[0]

Name     Arsalan
Age           24
City     Pulwama
Marks         85
Name: 0, dtype: object

In [45]:
df.loc[1,"City"]

'Delhi'

import pandas as pd

df = pd.DataFrame({
    "Name": ["Arsalan", "Rahul", "Ayesha", "Zaid", "Sara"],
    "Age": [24, 17, 22, 30, 19],
    "City": ["Pulwama", "Delhi", "Srinagar", "Delhi", "Mumbai"],
    "Marks": [85, 72, 91, 65, 88]
})

Find the highest Marks.

12. Find the lowest Marks.

13. Find the average Marks.

14. Find the total Marks.

15. Count the number of Names.

In [51]:
df["Marks"].min()

65

In [52]:
df["Marks"].mean()

np.float64(80.2)

In [53]:
df["Marks"].sum()

np.int64(401)

In [59]:
df["Name"].value_counts().sum()

np.int64(5)

Level 4 — Filtering

16. Display students whose Marks are greater than 80.

17. Display students whose Age is greater than 20.

18. Display students from Delhi.

19. Display students whose Marks are greater than 80 AND Age is greater than 20.

In [60]:
df[df["Marks"]>80]

      Name  Age      City  Marks
0  Arsalan   24   Pulwama     85
2   Ayesha   22  Srinagar     91
4     Sara   19    Mumbai     88

In [61]:
df[df["Age"]>20]

      Name  Age      City  Marks
0  Arsalan   24   Pulwama     85
2   Ayesha   22  Srinagar     91
3     Zaid   30     Delhi     65

In [62]:
df[df["City"]=="Delhi"]

    Name  Age   City  Marks
1  Rahul   17  Delhi     72
3   Zaid   30  Delhi     65

In [72]:
filtera=df[
    (df["Marks"]>80 )&
    (df["Age"]>20)
]

In [73]:
filtera

      Name  Age      City  Marks
0  Arsalan   24   Pulwama     85
2   Ayesha   22  Srinagar     91

Level 5 — Pandas skills

20. Sort the DataFrame by Marks from lowest to highest.

21. Sort it from highest to lowest.

22. Count how many students are from each city.

23. Find students whose City is either Delhi or Mumbai using isin().

24. Change "Arsalan" to "arsalan" using loc.

25. Use str.contains() to find names containing "a".

In [76]:
df.sort_values(by="Marks",ascending=True,inplace=True)

In [77]:
df

      Name  Age      City  Marks
3     Zaid   30     Delhi     65
1    Rahul   17     Delhi     72
0  Arsalan   24   Pulwama     85
4     Sara   19    Mumbai     88
2   Ayesha   22  Srinagar     91

In [78]:
df.sort_values(by="Marks",ascending=False,inplace=True)

In [79]:
df

      Name  Age      City  Marks
2   Ayesha   22  Srinagar     91
4     Sara   19    Mumbai     88
0  Arsalan   24   Pulwama     85
1    Rahul   17     Delhi     72
3     Zaid   30     Delhi     65

In [86]:
df["City"].value_counts()

City
Delhi       2
Srinagar    1
Mumbai      1
Pulwama     1
Name: count, dtype: int64

In [92]:
df[df["City"].isin(["Mumbai","Delhi"])]
# df[df['Name'].isin(['Braund, Mr. Owen Harris'])]

    Name  Age    City  Marks
4   Sara   19  Mumbai     88
1  Rahul   17   Delhi     72
3   Zaid   30   Delhi     65

In [93]:
df

      Name  Age      City  Marks
2   Ayesha   22  Srinagar     91
4     Sara   19    Mumbai     88
0  Arsalan   24   Pulwama     85
1    Rahul   17     Delhi     72
3     Zaid   30     Delhi     65

In [98]:
df.loc[df["Name"]=="Arsalan","Name"]="arsalan"

In [101]:
df

      Name  Age      City  Marks
2   Ayesha   22  Srinagar     91
4     Sara   19    Mumbai     88
0  arsalan   24   Pulwama     85
1    Rahul   17     Delhi     72
3     Zaid   30     Delhi     65

In [104]:
df.loc[df["Name"].str.contains("a",case=False,na=False),"Name"]

2     Ayesha
4       Sara
0    arsalan
1      Rahul
3       Zaid
Name: Name, dtype: object